services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.choices.event_listener.hook_listener:
    class: HeimrichHannot\ChoicesBundle\EventListener\HookListener
    public: true
    autowire: true