services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\ChoicesBundle\EventListener\AdjustFilterOptionsEventListener:
    public: false
    tags:
      - { name: kernel.event_listener, event: huh.filter.event.adjust_filter_options_event, method: onAdjustFilterOptions }


  # Hook Listener

  HeimrichHannot\ChoicesBundle\EventListener\HookListener: ~
  HeimrichHannot\ChoicesBundle\EventListener\LoadDataContainerListener: ~