services:
  _defaults:
    public: true
    autowire: true

  huh.choices.manager.choices_manager:
    class: HeimrichHannot\ChoicesBundle\Manager\ChoicesManager
  HeimrichHannot\ChoicesBundle\Manager\ChoicesManager: '@huh.choices.manager.choices_manager'

  HeimrichHannot\ChoicesBundle\Asset\FrontendAsset: ~