services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  HeimrichHannot\ChoicesBundle\:
    resource: "../src/{Asset,DataContainer,EventListener,Manager}/*"

  HeimrichHannot\ChoicesBundle\EventListener\AdjustFilterOptionsEventListener:
    public: false
    tags:
      - { name: kernel.event_listener, event: huh.filter.event.adjust_filter_options_event, method: onAdjustFilterOptions }